function createscatter(X1, Y1, S1, C1)
%CREATESCATTER(X1, Y1, S1, C1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c

%  Auto-generated by MATLAB on 22-Nov-2016 18:04:43

% Create scatter
scatter(X1,Y1,S1,C1);

