function [fitresult, gof] = createFitWB(HR,PC,threshold)
%CREATEFIT(LL,PC)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : LL
%      Y Output: PC
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Jan-2019 23:14:35


%% Fit: 'untitled fit 1'.
% load('Array.mat')
% close figure 3
LLfit = HR(1:end,1);
% minLev = min(LLfit);
% maxLev = max(LLfit);
% if minLev<0
%     LLfit = LLfit - minLev;
% end

PCfit = PC';
[xData, yData] = prepareCurveData( LLfit, PCfit );
a = threshold;
% Set up fittype and options.
ft = fittype( 'c-d.*exp(-(x./a)^b)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [a -0.005 -Inf -Inf];
opts.StartPoint = [0.0530446491219723 0.625734126909384 0.505508072942099 0.757740130578333];

figure( 'Name', 'Weibul fit' );
Checkfit = 2;
% while Checkfit == 2


% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
clf;
A = fitresult

% gets coefficients to calculate dynamic range of psych fxn
MyCoeffs = coeffvalues(fitresult);
Max=MyCoeffs(3)-MyCoeffs(4)*0.1;
Min=MyCoeffs(3)-MyCoeffs(4)*90;

% computes dyn range of psych fxn

Xatmax = solve((MyCoeffs(3)-MyCoeffs(4).*exp(-(x./MyCoeffs(1))^MyCoeffs(2)==Max),x);
Xatmin = solve((MyCoeffs(3)-MyCoeffs(4).*exp(-(x./MyCoeffs(1))^MyCoeffs(2)==Min),x);


% if minLev<0
% Xax =  minLev:0.1:maxLev;
% 
% plot(Xax,eq)
% else

h = plot( fitresult, xData, yData );
legend( h, 'PC vs. LL', 'untitled fit 1', 'Location', 'NorthEast' );
xlabel LL
ylabel PC
grid on;

end
% Checkfit =input('Enter 1 if fit is good or Enter 2: ');

% end
